"""Converts a fetched OpenStreetMap area (game/data/osm/<name>.json) into a game map
(game/maps/<name>.map.json) at 1 tile = 1 m, Zomboid scale.

    python tools/osm_import/convert.py riverview_centre

What it does:
- projects lat/lon to metres and rotates the area so its main street grid lines up with the
  game's tile axes (the game only has north/west walls, like Zomboid);
- paints ground: land use (grass, parks, woods, water, parking, farmland), then roads with
  widths by type, sidewalks along town streets, centre lines;
- rasterises building footprints and works out what each building is (house, apartments,
  store, pharmacy, gas station, restaurant, school, church...) from OSM tags and the shop/
  amenity points inside it. Real names are dropped: in game every business is a parody;
- places trees (OSM trees, woods, parks, a few in yards).
Building interiors are generated by the game (src/Core/Map/BuildingGen.cs), not here.
Map data © OpenStreetMap contributors, ODbL. The converter + fetch list recreate the map.
"""
import base64
import json
import math
import os
import sys

import numpy as np
from PIL import Image, ImageDraw

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
FLOORS = ["grass", "asphalt", "road_line", "road_line_y", "sidewalk", "driveway", "dirt", "water", "parking", "field", "void"]
F = {n: i for i, n in enumerate(FLOORS)}

ROAD_WIDTH = {
    "motorway": 14, "trunk": 13, "primary": 11, "secondary": 10, "tertiary": 9, "residential": 7,
    "unclassified": 7, "living_street": 6, "motorway_link": 7, "trunk_link": 7, "primary_link": 7,
    "secondary_link": 7, "tertiary_link": 7, "service": 4, "track": 3,
    "footway": 2, "path": 2, "cycleway": 2, "pedestrian": 4, "steps": 2,
}
TOWN_ROADS = {"primary", "secondary", "tertiary", "residential", "unclassified", "living_street", "trunk"}
SHOP_KINDS = {
    "convenience": "convenience", "chemist": "pharmacy", "pharmacy": "pharmacy", "supermarket": "grocery",
    "greengrocer": "grocery", "bakery": "grocery", "hardware": "hardware", "doityourself": "hardware",
    "department_store": "bigbox", "variety_store": "bigbox", "clothes": "clothing", "shoes": "clothing",
    "alcohol": "liquor", "beverages": "liquor", "car_repair": "garage", "car": "garage", "tyres": "garage",
}
AMENITY_KINDS = {
    "pharmacy": "pharmacy", "fuel": "gas_station", "fast_food": "restaurant", "restaurant": "restaurant",
    "cafe": "restaurant", "pub": "bar", "bar": "bar", "school": "school", "kindergarten": "school",
    "place_of_worship": "church", "hospital": "hospital", "clinic": "clinic", "doctors": "clinic",
    "dentist": "clinic", "police": "police", "fire_station": "fire_station", "bank": "office",
    "library": "office", "townhall": "office", "post_office": "office", "community_centre": "office",
}
BUILDING_KINDS = {
    "house": "house", "detached": "house", "semidetached_house": "house", "bungalow": "house",
    "residential": "house", "terrace": "house", "apartments": "apartments", "garage": "garage_shed",
    "garages": "garage_shed", "shed": "garage_shed", "retail": "retail", "commercial": "retail",
    "supermarket": "grocery", "school": "school", "church": "church", "industrial": "warehouse",
    "warehouse": "warehouse", "office": "office", "hospital": "hospital",
}


class Projector:
    def __init__(self, bbox):
        s, w, n, e = bbox
        self.lat0, self.lon0 = (s + n) / 2, (w + e) / 2
        self.kx = 111320 * math.cos(math.radians(self.lat0))
        self.ky = 110540
        self.angle = 0.0
        self.off = (0.0, 0.0)

    def raw(self, lat, lon):
        return ((lon - self.lon0) * self.kx, -(lat - self.lat0) * self.ky)

    def __call__(self, lat, lon):
        x, y = self.raw(lat, lon)
        c, s = math.cos(-self.angle), math.sin(-self.angle)
        return (x * c - y * s - self.off[0], x * s + y * c - self.off[1])


def dominant_angle(ways, proj):
    """Main street-grid direction, so the map can be turned to line streets up with tiles."""
    hist = np.zeros(90)
    for w in ways:
        hw = w.get("tags", {}).get("highway")
        if hw not in TOWN_ROADS:
            continue
        pts = [proj.raw(p["lat"], p["lon"]) for p in w.get("geometry", [])]
        for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
            L = math.hypot(x1 - x0, y1 - y0)
            a = math.degrees(math.atan2(y1 - y0, x1 - x0)) % 90
            hist[int(a) % 90] += L
    if hist.sum() == 0:
        return 0.0
    # smooth circularly, take the peak
    k = np.array([1, 2, 3, 2, 1], dtype=float)
    sm = sum(np.roll(hist, i - 2) * k[i] for i in range(5))
    a = float(np.argmax(sm)) + 0.5
    return math.radians(a if a < 45 else a - 90)


def poly(geom, proj):
    return [proj(p["lat"], p["lon"]) for p in geom if p]


def main(name):
    src = json.load(open(os.path.join(ROOT, "game", "data", "osm", name + ".json")))
    bbox = src["ztown"]["bbox"]
    els = src["elements"]
    ways = [e for e in els if e["type"] == "way" and "geometry" in e]
    rels = [e for e in els if e["type"] == "relation"]
    nodes = [e for e in els if e["type"] == "node"]

    proj = Projector(bbox)
    proj.angle = dominant_angle(ways, proj)
    # bounds of the rotated bbox corners
    s, w, n, e = bbox
    corners = [proj(la, lo) for la, lo in ((s, w), (s, e), (n, w), (n, e))]
    minx, miny = min(c[0] for c in corners), min(c[1] for c in corners)
    proj.off = (minx, miny)
    corners = [proj(la, lo) for la, lo in ((s, w), (s, e), (n, w), (n, e))]
    W = int(math.ceil(max(c[0] for c in corners))) + 1
    H = int(math.ceil(max(c[1] for c in corners))) + 1
    print(f"{name}: {W}x{H} tiles, grid turned {math.degrees(proj.angle):.1f}°")

    def canvas(fill=0):
        return Image.new("L", (W, H), fill)

    # inside the real bbox (the rotated rectangle); outside is the map edge
    inside = canvas()
    ImageDraw.Draw(inside).polygon([corners[0], corners[1], corners[3], corners[2]], fill=1)
    inside = np.asarray(inside, dtype=bool)

    floor = np.full((H, W), F["grass"], dtype=np.uint8)
    trees_wanted = np.zeros((H, W), dtype=np.float32)
    rng = np.random.default_rng(abs(hash(name)) % (2 ** 32))

    def fill_polys(polys, value, target=floor):
        img = Image.fromarray(target)
        d = ImageDraw.Draw(img)
        for p in polys:
            if len(p) >= 3:
                d.polygon(p, fill=int(value))
        target[:] = np.asarray(img)

    def area_polys(el):
        if el["type"] == "way":
            return [poly(el["geometry"], proj)]
        out = []
        for m in el.get("members", []):
            if m.get("role") in ("outer", "") and "geometry" in m:
                out.append(poly(m["geometry"], proj))
        return out

    # ---- land use / natural
    for el in ways + rels:
        t = el.get("tags", {})
        lu, nat, lei = t.get("landuse"), t.get("natural"), t.get("leisure")
        polys = area_polys(el)
        if nat == "water" or lu in ("reservoir", "basin") or t.get("waterway") == "riverbank":
            fill_polys(polys, F["water"])
        elif lu in ("forest",) or nat in ("wood", "scrub"):
            m = canvas()
            fill_polys(polys, 1, target=np.asarray(m).copy()) if False else None
            mask = Image.new("L", (W, H), 0)
            dd = ImageDraw.Draw(mask)
            for p in polys:
                if len(p) >= 3:
                    dd.polygon(p, fill=1)
            trees_wanted = np.maximum(trees_wanted, np.asarray(mask, dtype=np.float32) * 0.09)
        elif lu in ("farmland", "meadow") or nat in ("grassland",):
            fill_polys(polys, F["field"])
        elif lu in ("construction", "brownfield", "landfill", "quarry"):
            fill_polys(polys, F["dirt"])
        elif t.get("amenity") == "parking" or lu == "garages":
            fill_polys(polys, F["parking"])
        elif lei in ("park", "pitch", "playground", "garden") or lu in ("grass", "recreation_ground", "cemetery"):
            mask = Image.new("L", (W, H), 0)
            dd = ImageDraw.Draw(mask)
            for p in polys:
                if len(p) >= 3:
                    dd.polygon(p, fill=1)
            trees_wanted = np.maximum(trees_wanted, np.asarray(mask, dtype=np.float32) * 0.012)

    # ---- waterways (lines)
    img = Image.fromarray(floor)
    d = ImageDraw.Draw(img)
    for el in ways:
        ww = el.get("tags", {}).get("waterway")
        if ww in ("river", "stream", "canal", "ditch", "drain"):
            width = {"river": 30, "canal": 10, "stream": 3}.get(ww, 2)
            d.line(poly(el["geometry"], proj), fill=F["water"], width=width)
    floor = np.asarray(img).copy()

    # ---- roads: sidewalks first (wider), then the road on top, then centre lines
    road_ways = [el for el in ways if el.get("tags", {}).get("highway") in ROAD_WIDTH and el.get("tags", {}).get("area") != "yes"]
    road_ways.sort(key=lambda el: ROAD_WIDTH[el["tags"]["highway"]])
    side = Image.new("L", (W, H), 0)
    sd = ImageDraw.Draw(side)
    road = Image.new("L", (W, H), 0)
    rd = ImageDraw.Draw(road)
    path = Image.new("L", (W, H), 0)
    pd_ = ImageDraw.Draw(path)
    centre_x = Image.new("L", (W, H), 0)
    centre_y = Image.new("L", (W, H), 0)
    cxd, cyd = ImageDraw.Draw(centre_x), ImageDraw.Draw(centre_y)
    for el in road_ways:
        hw = el["tags"]["highway"]
        pts = poly(el["geometry"], proj)
        if len(pts) < 2:
            continue
        width = ROAD_WIDTH[hw]
        if el["tags"].get("lanes", "").isdigit():
            width = max(width, int(el["tags"]["lanes"]) * 3.5)
        if hw in ("footway", "path", "cycleway", "steps", "pedestrian", "track"):
            pd_.line(pts, fill=2 if hw == "track" else 1, width=int(width))
            continue
        if hw in TOWN_ROADS:
            sd.line(pts, fill=1, width=int(width + 4))
            for p in pts:
                sd.ellipse([p[0] - (width + 4) / 2, p[1] - (width + 4) / 2, p[0] + (width + 4) / 2, p[1] + (width + 4) / 2], fill=1)
        rd.line(pts, fill=1, width=int(width))
        for p in pts:
            rd.ellipse([p[0] - width / 2, p[1] - width / 2, p[0] + width / 2, p[1] + width / 2], fill=1)
        if width >= 7 and hw != "service":
            for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
                if abs(x1 - x0) >= abs(y1 - y0):
                    cxd.line([(x0, y0), (x1, y1)], fill=1, width=1)
                else:
                    cyd.line([(x0, y0), (x1, y1)], fill=1, width=1)
    side, road, path = np.asarray(side, bool), np.asarray(road, bool), np.asarray(path)
    land = ~np.isin(floor, [F["water"]])
    floor[side & land & ~road] = F["sidewalk"]
    floor[path == 1] = F["sidewalk"]
    floor[path == 2] = F["dirt"]
    floor[road] = F["asphalt"]
    floor[road & np.asarray(centre_x, bool)] = F["road_line"]
    floor[road & np.asarray(centre_y, bool) & ~np.asarray(centre_x, bool)] = F["road_line_y"]

    # ---- buildings
    bid = np.zeros((H, W), dtype=np.int32)
    buildings = []
    pois = []
    for nd in nodes:
        t = nd.get("tags", {})
        kind = SHOP_KINDS.get(t.get("shop", "")) or AMENITY_KINDS.get(t.get("amenity", ""))
        if t.get("shop") and not kind:
            kind = "retail"
        if kind:
            x, y = proj(nd["lat"], nd["lon"])
            pois.append((x, y, kind))
    bimg = Image.fromarray(bid.astype(np.int32), "I")
    bd = ImageDraw.Draw(bimg)
    meta = {}
    for el in ways + rels:
        t = el.get("tags", {})
        if "building" not in t:
            continue
        polys = area_polys(el)
        if not polys or len(polys[0]) < 3:
            continue
        idx = len(meta) + 1
        kind = (SHOP_KINDS.get(t.get("shop", "")) or AMENITY_KINDS.get(t.get("amenity", ""))
                or BUILDING_KINDS.get(t.get("building", ""), "house" if t.get("building") == "yes" else "retail"))
        levels = t.get("building:levels", "1")
        meta[idx] = {"osm": f"{el['type'][0]}{el['id']}", "kind": kind,
                     "levels": int(levels) if str(levels).isdigit() else 1, "tagged": t.get("building")}
        for p in polys:
            bd.polygon(p, fill=idx)
    bid = np.asarray(bimg, dtype=np.int32).copy()
    bid[~inside] = 0
    # shops/amenities inside a footprint decide what the building is
    for x, y, kind in pois:
        xi, yi = int(x), int(y)
        if 0 <= xi < W and 0 <= yi < H and bid[yi, xi]:
            meta[bid[yi, xi]]["kind"] = kind
    # buildings cut off by the map edge are dropped; buildings are on land, so keep a strip of
    # land around each one (wide river lines otherwise swallow riverside yards)
    from PIL import ImageFilter
    edge_zone = np.asarray(Image.fromarray((~inside).astype(np.uint8) * 255).filter(ImageFilter.MaxFilter(7)), bool)
    for idx in list(meta):
        if (edge_zone & (bid == idx)).any():
            bid[bid == idx] = 0
    around = np.asarray(Image.fromarray((bid > 0).astype(np.uint8) * 255).filter(ImageFilter.MaxFilter(7)), bool)
    floor[around & (floor == F["water"])] = F["grass"]
    for idx, m in meta.items():
        ys, xs = np.nonzero(bid == idx)
        if len(xs) < 12:      # too small to walk into (sheds become solid props later)
            bid[bid == idx] = 0
            continue
        runs = []
        for y in np.unique(ys):
            row = np.sort(xs[ys == y])
            start = prev = row[0]
            for x in row[1:]:
                if x != prev + 1:
                    runs.append([int(y), int(start), int(prev + 1)])
                    start = x
                prev = x
            runs.append([int(y), int(start), int(prev + 1)])
        m["runs"] = runs
        m["id"] = f"b{idx}"
        m["area"] = int(len(xs))
        buildings.append(m)
        floor[bid == idx] = F["grass"]  # interiors set by the game
    # yards next to houses get the odd driveway: leave as grass for now

    # ---- trees
    objects = []
    for nd in nodes:
        if nd.get("tags", {}).get("natural") == "tree":
            x, y = proj(nd["lat"], nd["lon"])
            objects.append([int(x), int(y), "tree"])
    yard = (floor == F["grass"]) & (bid == 0) & inside
    # a few yard trees, kept off roads and building walls
    near_build = np.zeros_like(yard)
    near_build[1:-1, 1:-1] = (bid[:-2, 1:-1] | bid[2:, 1:-1] | bid[1:-1, :-2] | bid[1:-1, 2:]) > 0
    p = np.where(yard & ~near_build, 0.004, 0.0) + np.where(yard, trees_wanted, 0)
    ys, xs = np.nonzero(rng.random((H, W)) < p)
    for x, y in zip(xs, ys):
        objects.append([int(x), int(y), "tree"])

    floor[~inside] = F["void"]

    out = {
        "name": name, "width": W, "height": H, "bbox": bbox,
        "rotationDeg": round(math.degrees(proj.angle), 2),
        "attribution": "Map data © OpenStreetMap contributors, ODbL 1.0",
        "floorPalette": FLOORS,
        "floors": base64.b64encode(floor.tobytes()).decode(),
        "buildings": buildings,
        "objects": objects,
    }
    os.makedirs(os.path.join(ROOT, "game", "maps"), exist_ok=True)
    path_out = os.path.join(ROOT, "game", "maps", name + ".map.json")
    with open(path_out, "w") as f:
        json.dump(out, f, separators=(",", ":"))
    kinds = {}
    for b in buildings:
        kinds[b["kind"]] = kinds.get(b["kind"], 0) + 1
    print(f"  {len(buildings)} buildings {kinds}, {len(objects)} trees -> {os.path.relpath(path_out, ROOT)} ({os.path.getsize(path_out) // 1024} KB)")
    # preview image
    pal = np.array([[93, 108, 61], [76, 75, 74], [190, 160, 70], [190, 160, 70], [156, 152, 144], [110, 103, 92],
                    [120, 98, 70], [70, 100, 130], [90, 90, 92], [140, 150, 80], [20, 20, 20]], dtype=np.uint8)
    prev = pal[floor].copy()
    prev[bid > 0] = [200, 190, 175]
    Image.fromarray(prev).save(os.path.join(ROOT, "game", "maps", name + ".preview.png"))


if __name__ == "__main__":
    for n in sys.argv[1:]:
        main(n)
